language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer install --prefer-dist
  - mkdir -p build/logs

script:
  - php artisan migrate
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v;
