language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=SomeRandomString
    - DB_DATABASE=testing
    - DB_USERNAME=root
    - DB_PASSWORD=
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

before_script:
  - mysql -e 'create database testing;'
  - composer install --prefer-dist
  - mkdir -p build/logs

script:
  - php artisan migrate
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v;
